# Generated by Django 6.0.7 on 2026-07-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('SIM_CARD', 'SIM card'), ('ONT_DEVICE', 'ONT / fiber device')], max_length=20)),
                ('batch_reference', models.CharField(blank=True, max_length=50)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('quantity_reserved', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.product')),
            ],
        ),
    ]
