# Generated by Django 6.0.7 on 2026-07-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_type', models.CharField(choices=[('VOICE', 'Voice call'), ('DATA', 'Data session'), ('SMS', 'SMS')], default='DATA', max_length=20)),
                ('data_mb', models.FloatField(default=0)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('charge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='service_inventory.service')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
