# Generated by Django 6.0.7 on 2026-07-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('MSISDN', 'Mobile number (MSISDN)'), ('FIBER_PORT', 'Fiber ONT port')], max_length=20)),
                ('identifier', models.CharField(help_text='MSISDN number or port ID, e.g. ONT-0234', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('FREE', 'Free'), ('RESERVED', 'Reserved'), ('ASSIGNED', 'Assigned'), ('FAULTY', 'Faulty')], default='FREE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='orders.order')),
            ],
            options={
                'ordering': ['resource_type', 'identifier'],
            },
        ),
    ]
