# Generated by Django 6.0.7 on 2026-07-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('product_type', models.CharField(choices=[('PREPAID_SIM', 'Mobile Prepaid SIM'), ('FIBER', 'Home Fiber Broadband')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('validity_days', models.IntegerField(blank=True, help_text='Prepaid: pack validity', null=True)),
                ('data_per_day_gb', models.FloatField(blank=True, help_text='Prepaid: daily data allowance', null=True)),
                ('voice_minutes', models.IntegerField(blank=True, help_text='Prepaid: voice minutes included', null=True)),
                ('speed_mbps', models.IntegerField(blank=True, help_text='Fiber: download speed', null=True)),
                ('monthly_data_cap_gb', models.IntegerField(blank=True, help_text='Fiber: FUP data cap, blank=unlimited', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='catalog.product')),
            ],
        ),
    ]
